version: '3.8'

services:
  app:
    image: kimseonhee126/inu-festival-be
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=root1!
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx sequelize-cli db:migrate && npm start"

  db:
    image: mysql:8.0
    container_name: mysql-8
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER : ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: inu_festival_be
      MYSQL_PASSWORD : root1!
    volumes:
      - db_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
