# Node.js API

# GET 요청: 메인 페이지 - 오늘의 라인업
###
GET http://localhost:4000/timetable

# GET 요청: 메인 페이지 - 부스 랭킹 Top 5
###
GET http://localhost:5000/ranking

# GET 요청: 메인 페이지 - 한 줄 외치기
###
GET http://localhost:5000/shout

# GET 요청: 메인 페이지 - 한 줄 외치기 `키워드`
###
GET http://localhost:5000/keyword

# GET 요청: 유저 목록
###
GET http://localhost:5000/user

# GET 요청: 공지 목록
###
GET http://localhost:5000/notices

# 그냥 연습...신경 ㄴㄴ
###
GET http://localhost:5000/perform/celeb
###
GET http://localhost:5000/perform/student
###
GET http://localhost:5000/perform/celeb
