# Node.js API

# GET 요청: 메인 페이지 - 오늘의 라인업
###
GET http://localhost:4000/timetable

# GET 요청: 메인 페이지 - 부스 랭킹 Top 5
###
GET http://localhost:4000/booth/ranking

# GET 요청: - 부스 전체
###
GET http://localhost:4000/booth/1

# GET 요청: - 부스 하나
###
GET http://localhost:4000/booth/all

# GET 요청: 메인 페이지 - 한 줄 외치기
###
GET http://localhost:4000/shout

# GET 요청: 메인 페이지 - 한 줄 외치기 `키워드`
###
GET http://localhost:4000/keyword

# GET 요청: 공지 목록
###
GET http://localhost:4000/notice

# GET 요청: 부스 댓글 목록
###
GET http://localhost:4000/booth/comment/1

# GET 요청: 부스 필터 카테고리 목록
###
GET http://localhost:4000/booth/category

###

# POST 요청: 관리자 부스 추가
###
POST http://localhost:4000/admin/booth
Content-Type: application/json

{
    "name": "test1",
    "category": "비주점",
    "department": "희희낙락",
    "description": "test1",
    "liked": 0
}

# POST 요청: 부스 댓글 추가
###
POST http://localhost:4000/booth/comment/1
Content-Type: application/json

{
    "content": "새로운댓글1",
    "emoji": "happy",
    "boothId": 1
}

# PUT 요청: 좋아요 추가
###
PUT http://localhost:4000/booth/liked/1
Content-Type: application/json

{
    "likeCount": 22
}



# POST 요청: 로그인
###
POST http://localhost:4000/user/lms
Content-Type: application/json

{
    "studentId": "201901284",
    "password": "rootroot1!"    
}

# GET 요청: 부스 필터 카테고리 목록
###
GET http://localhost:4000/user/logout
authorization: Bearer 1eed0056-accb-6ac0-f3fd-6db2104f0332


# {
#     "statusCode": 401,
#     "error": "invalid_credentials",
#     "message": "학번과 비밀번호를 확인해 주세요 😉"
# }

# {
#     "rememberMeToken": "1eecfcfc-abcb-6a10-9e0b-6a59786c245c",
#     "barcode": "1211407704"
# }



# PUT 요청 : 관리자 부스 수정
###
PUT http://localhost:4000/admin/booth

# 그냥 연습...신경 ㄴㄴ
###
GET http://localhost:5000/perform/celeb
###
GET http://localhost:5000/perform/student
###
GET http://localhost:5000/perform/celeb
